Various small changes
radio - removed 'play' command
lock - added support for themes
mpv - open current file in dragon

diff --git a/bin/bin/utils/lock b/bin/bin/utils/lock
--- a/bin/bin/utils/lock
+++ b/bin/bin/utils/lock
@@ -2,21 +2,23 @@
 #
 # by Siddharth Dushantha
 #
-# Since I use betterlockscreen as my greeter, instead of something like
-# GDM, I need to make sure, that there is an image it can use for the
-# lockscreen or else betterlockscreen will crash. This creates a security hole
-# in my system. Since I have autologin, betterlockscreen is my only security
-# I have.
+# Lock the screen using i3lock but with a chosen theme location in
+# $HOME/.config/lockscreen/
+# 
+
+lockscreen_config_dir="$HOME/.config/lockscreen"
+default_theme="CalvinAndHobbes"
 
 # Send the pause key to all mpv videos
 # before locking the screen
 pauseallmpv > /dev/null 2>&1
 
-output=$(betterlockscreen -l)
-currenWall="$HOME/pictures/current/*"
+input="$1"
+[ -z "$input" ] && input="$default_theme"
 
-if [[ $output == *"Could not open directory"* ]]; then
-    dunstify "Lockscreen" "Updating image..."
-    betterlockscreen -u "$currenWall"
-    betterlockscreen -l
-fi
+themes=$(find "$lockscreen_config_dir" ! -path . -type d -exec basename {} \;)
+theme=$(echo "$themes" | grep -i "$input" | head -n1)
+
+[ -z "$theme" ] && printf %s "Error: $input is an invalid theme" && exit 1
+
+bash "$lockscreen_config_dir/$theme/lock.sh"
