qrcode: added dependency check and cleaned a few things up

diff --git a/bin/bin/utils/qrshot b/bin/bin/utils/qrshot
--- a/bin/bin/utils/qrshot
+++ b/bin/bin/utils/qrshot
@@ -7,6 +7,19 @@
 
 image_file="/tmp/ocr.png"
 
+# Check if the needed dependencies are installed
+dependencies=(maim notify-send zbarimg xclip)
+for dependency in "${dependencies[@]}"; do
+    type -p "$dependency" &>/dev/null || {
+        # The reason why we are sending the error as a notification is because
+        # user is most likely going to run this script by binding it to their
+        # keyboard, therefor they cant see any text that is outputed using echo
+        notify-send "ocr" "Could not find '${dependency}', is it installed?"
+        echo "Could not find '${dependency}', is it installed?"
+        exit 1
+    }
+done
+
 # Take screenshot by selecting the area
 maim -s "$image_file"
 
@@ -20,13 +33,20 @@ status=$?
 # taking a screenshot, then just exit
 [ $status -ne 0 ] && exit 1
 
-output=$(zbarimg "$image_file" -q | sed "s/QR-Code://")
+# Use zbarimg to decode the text from the QR code and remove
+# the unecessary "QR-Code://" prefix
+decoded_text=$(zbarimg "$image_file" -q | sed "s/QR-Code://")
 
-if [ -z "$output" ]; then
-    notify-send "ocr" "no text was detected"
+if [ -z "$decoded_text" ]; then
+    notify-send "qrshot" "no text was detected"
     exit 1
 fi
 
 # Copy text to clipboard
-printf %b "$output" | xclip -selection clip
+printf %b "$decoded_text" | xclip -selection clip
 
+# Let us know that something was decoded
+notify-send "qrshot" "$decoded_text"
+
+# Cleaning up the trash that was left behind
+rm $image_file
